# 1. Create a secret store via GCP Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-storage
spec:
  provider:
    gcpsm:
      projectID: ""
---
# 2. Declare the secret synchronization from GCP Secret Manager to K8s
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sync-postgres-credentials
