apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-jwt-sync
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-storage
    kind: ClusterSecretStore
  target:
    name: keycloak-jwt-credential
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          konghq.com/credential: jwt
      data:
        algorithm: "{{ .algorithm }}"
        key: "{{ .key }}"
        rsa_public_key: |
          -----BEGIN PUBLIC KEY-----
          {{ .rsa_public_key }}
          -----END PUBLIC KEY-----
  data:
    - secretKey: algorithm
      remoteRef:
        key: keycloak-jwt-credential
        property: algorithm
    - secretKey: key
      remoteRef:
        key: keycloak-jwt-credential
        property: key
    - secretKey: rsa_public_key
      remoteRef:
        key: keycloak-jwt-credential
        property: rsa_public_key
