apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../../base/api-gateway
  - keycloak-external-secret.yaml

patches:
  - target:
      kind: Ingress
      name: api-gateway-ingress
    path: ingress-patch.yaml
