apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../../base/backtesting-service

images:
  - name: backtesting-service
    newName: asia-southeast1-docker.pkg.dev/flying-coin-489803/flying-coin-docker/backtesting-service
    newTag: staging
