apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: market-data-db-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-storage
    kind: ClusterSecretStore
  target:
    name: market-data-db-config
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "{{ .db_url }}"          
  data:
    - secretKey: db_url
      remoteRef:
        key: market-data-db-url
    
