apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forecast-db-sync
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-storage
    kind: ClusterSecretStore
  target:
    name: forecast-db-config
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "{{ .db_url | toString | trim }}"
        RABBITMQ_URL: "{{ .rabbitmq_url | toString | trim }}"
  data:
    - secretKey: db_url
      remoteRef:
        key: market-data-db-url # Dùng chung URL vì dùng cùng DB market_data
    - secretKey: rabbitmq_url
      remoteRef:
        key: rabbitmq-url
