apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../../base/forecast-service
  - database-external-secret.yaml

images:
  - name: forecast-service
    newName: asia-southeast1-docker.pkg.dev/flying-coin/flying-coin/forecast-service
    newTag: latest

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: forecast-service-deployment
    spec:
      template:
        spec:
          containers:
            - name: forecast-service
              envFrom:
                - secretRef:
                    name: forecast-db-config
              env:
                - name: MLFLOW_TRACKING_URI
                  value: "http://mlflow-service.mlops.svc.cluster.local:5000"
                - name: RABBITMQ_URL
                  value: "amqp://admin:admin@rabbitmq-service.database.svc.cluster.local:5672/"
