apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-db-sync
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-storage
    kind: ClusterSecretStore
  target:
    name: portfolio-db-config
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: portfolio-db-url
    - secretKey: REDIS_URL
      remoteRef:
        key: redis-url
