apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: portfolio-db-sync
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-storage
    kind: ClusterSecretStore
  target:
    name: portfolio-db-config
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "{{ .db_url | toString | trim }}"
        REDIS_URL: "{{ .redis_url | toString | trim }}"
  data:
    - secretKey: db_url
      remoteRef:
        key: portfolio-db-url
    - secretKey: redis_url
      remoteRef:
        key: redis-url
