apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sentiment-db-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-storage
    kind: ClusterSecretStore
  target:
    name: sentiment-db-config
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "{{ .db_url }}"          
        NEWSAPI_KEY: "{{ .newsapi_key }}"
  data:
    - secretKey: db_url
      remoteRef:
        key: market-data-db-url
    - secretKey: newsapi_key
      remoteRef:
        key: newsapi-key
