apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../../base/sentiment-service
  - database-external-secret.yaml

images:
  - name: sentiment-service
    newName: asia-southeast1-docker.pkg.dev/flying-coin/flying-coin/sentiment-service
    newTag: latest

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sentiment-service-deployment
    spec:
      template:
        spec:
          containers:
            - name: sentiment-service
              envFrom:
                - secretRef:
                    name: sentiment-db-config
