apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../../base/market-data-service
  - configmap-db.yaml

images:
  - name: market-data-service
    newTag: local

patches: 
  - path: patch-imagepull.yaml
    target:
      kind: Deployment
      name: market-data-service-deployment