apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-service-deployment
spec:
  template:
    spec:
      containers:
        - name: market-data-service
          imagePullPolicy: Never
