apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ssh-bastion-host-keys
  namespace: mlops
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-storage
  target:
    name: ssh-bastion-host-keys
    creationPolicy: Owner
  data:
    - secretKey: ssh_host_rsa_key
      remoteRef:
        key: ssh-bastion-host-rsa-key
    - secretKey: ssh_host_ecdsa_key
      remoteRef:
        key: ssh-bastion-host-ecdsa-key
    - secretKey: ssh_host_ed25519_key
      remoteRef:
        key: ssh-bastion-host-ed25519-key
