apiVersion: apps/v1
kind: Deployment
metadata:
  name: backtesting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backtesting-service
  template:
    metadata:
      labels:
        app: backtesting-service
    spec:
      containers:
      - name: backtesting-service
        image: asia-southeast1-docker.pkg.dev/flying-coin-489803/flying-coin-docker/backtesting-service:staging
        ports:
        - containerPort: 8000
        env:
        - name: MARKET_DATA_SERVICE_URL
          value: "http://market-data-service-service:8001"
