apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-origin-tls
  namespace: kong # Đảm bảo đúng namespace cài Kong
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-storage # Tên ClusterSecretStore bạn đã định nghĩa cho GCP
  target:
    name: cloudflare-origin-tls # Tên Secret thật mọc ra để Kong dùng
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls # CRITICAL: Bắt buộc type này thì Nginx/Kong mới nhận làm SSL
      data:
        tls.crt: "{{ .cloudflare_cert }}"
        tls.key: "{{ .cloudflare_key }}"
  data:
  - secretKey: cloudflare_cert
    remoteRef:
      key: kong-cloudflare-cert # Tên Secret quản lý trên GCP Secret Manager
  - secretKey: cloudflare_key
    remoteRef:
      key: kong-cloudflare-key  # Tên Secret quản lý trên GCP Secret Manager
