apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops

resources:
  - ../../../../base/mlops/mlflow
  - serviceaccount.yaml
  - mlflow-external-secret.yaml

patches:
  - path: configmap-patch.yaml
  - path: patch-sa.yaml
