apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-sa
  namespace: mlops
  annotations:
    # Workload Identity: bind K8s SA → GCP SA để truy cập GCS không cần credentials file
    iam.gke.io/gcp-service-account: "mlflow@flying-coin.iam.gserviceaccount.com"
