apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  annotations:
    # Khai báo cho K8s biết Ingress này do Kong đóng vai trò Controller xử lý phân giải
    kubernetes.io/ingress.class: kong
    # Kích hoạt các Plugin đã định nghĩa sẵn cho toàn bộ các Route nằm trong Ingress này
    # Ở đây ta bật CORS (để Frontend gọi API không bị chặn cross-origin) và Rate Limit (chống Spam)
    konghq.com/plugins: "global-cors, global-rate-limit, keycloak-jwt-auth"
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - flying-coin.thinhopsops.win # Sẽ được ghi đè nếu cần, nhưng để mặc định ở đây cho tiện
      secretName: cloudflare-origin-tls
  rules:
    - host: flying-coin.thinhopsops.win
      http:
        paths:
          
          # Route 2: Phục vụ riêng cho Market Data Service (Scrape/Feed giá crypto, CP sau này)
          - path: /api/v1/market-data
            pathType: Prefix
            backend:
              service:
                name: market-data-service-service # Tên thực của Service Python sau này ta sẽ Deploy
                port:
                  number: 8001
          
          # Route 3: Phục vụ Sentiment Analysis service
          - path: /api/v1/sentiment
            pathType: Prefix
            backend:
              service:
                name: sentiment-service-service
                port:
                  number: 8002
          
          # Route 4: Web Frontend (Moved to public-ingress.yaml)
          # - path: /
          #   ...
          
          # Route 5: Collectors service
          - path: /api/v1/collectors
            pathType: Prefix
            backend:
              service:
                name: collectors-service
                port:
                  number: 8000
          
          # Route 6: Forecast service
          - path: /api/v1/forecast
            pathType: Prefix
            backend:
              service:
                name: forecast-service-service
                port:
                  number: 8000
          
          # Route 7: Backtest service
          - path: /api/v1/backtest
            pathType: Prefix
            backend:
              service:
                name: backtesting-service
                port:
                  number: 8000
          
          # Route 8: Portfolio service
          - path: /api/v1/portfolios
            pathType: Prefix
            backend:
              service:
                name: portfolio-service
                port:
                  number: 8000
          
          # Route 9: Notification service
          - path: /api/v1/notification
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 80
