# Chức năng: Là file "Hợp Nhất Tập Hợp" của thư mục base/api-gateway.
# Khi bạn gõ chạy lệnh `kubectl apply -k .`, Kubernetes (Kustomize) sẽ tự động tìm quét file kustomization.yaml này đầu tiên,
# và sau đó lần lượt nạp, apply tất cả con cài đặt theo danh sách resources bên dưới.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml           # Tên cũ là api-ingress, chứa các Route cần JWT
  - public-ingress.yaml    # Chứa Route cho Frontend (Public)
  - kong-plugins.yaml      # Tự động apply các Plugin giúp thiết lập hành vi của KONG
  - keycloak-consumer.yaml # KongConsumer + JWT credential để verify Keycloak token (RS256)
