apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- ../../../base/forecast-service

images:
  - name: forecast-service
    newTag: local-v2

patches:
  - path: patch-imagepull.yaml
    target:
      kind: Deployment
      name: forecast-service-deployment
