apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sync-redis-credentials
  namespace: database
spec:
  refreshInterval: "1h" # Secret update frequency (1 hour)
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-storage # ClusterSecretStore created during Postgres setup
  target:
    name: redis-credentials # K8s Secret name to be CREATED (Matches auth.existingSecret in redis-gcp.yaml)
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: redis-password
