apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: collectors-db-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-storage
    kind: ClusterSecretStore
  target:
    name: collectors-db-config
    creationPolicy: Owner
    template:
      data:
        NEWSAPI_KEY: "{{ .newsapi_key }}"
  data:
    - secretKey: newsapi_key
      remoteRef:
        key: newsapi-key
