apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: collectors-db-sync
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-storage
    kind: ClusterSecretStore
  target:
    name: collectors-db-config
    creationPolicy: Owner
    template:
      data:
        NEWSAPI_KEY: "{{ .newsapi_key | toString | trim }}"
        RABBITMQ_URL: "{{ .rabbitmq_url | toString | trim }}"
        REDIS_URL: "{{ .redis_url | toString | trim }}"
  data:
    - secretKey: newsapi_key
      remoteRef:
        key: newsapi-key
    - secretKey: rabbitmq_url
      remoteRef:
        key: rabbitmq-url
    - secretKey: redis_url
      remoteRef:
        key: redis-url
