apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sync-rabbitmq-credentials
  namespace: database
spec:
  refreshInterval: "1h" # Secret update frequency (1 hour)
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-storage # ClusterSecretStore created during Postgres setup
  target:
    name: rabbitmq-credentials # K8s Secret name to be CREATED (Matches auth.existingPasswordSecret in rabbitmq-gcp.yaml)
    creationPolicy: Owner
  data:
    - secretKey: rabbitmq-password # This key matches auth.existingSecretPasswordKey
      remoteRef:
        key: rabbitmq-password
