apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-secrets
  namespace: mlops
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-storage
  target:
    name: airflow-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: airflow-db-password
    - secretKey: admin-password
      remoteRef:
        key: airflow-admin-password
