apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-secrets-sync
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-storage
    kind: ClusterSecretStore
  target:
    name: notification-secrets
    creationPolicy: Owner
    template:
      data:
        REDIS_URL: "{{ .redis_url | toString | trim }}"
        SMTP_USER: "{{ .smtp_user | toString | trim }}"
        SMTP_PASS: "{{ .smtp_pass | toString | trim }}"
  data:
    - secretKey: redis_url
      remoteRef:
        key: redis-url
    - secretKey: smtp_user
      remoteRef:
        key: notification-smtp-user
    - secretKey: smtp_pass
      remoteRef:
        key: notification-smtp-pass
