apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-secret-store.yaml
  - infra-external-secret.yaml
  - postgres-external-secret.yaml
  - redis-external-secret.yaml
  - rabbitmq-external-secret.yaml
  - airflow-external-secret.yaml
