# Sync redis-password từ GCP Secret Manager → K8s Secret "redis-credentials"
# Helm chart redis-gcp.yaml dùng existingSecret: "redis-credentials"
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sync-redis-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-storage
  target:
    name: redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: redis-password
