apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-frontend-secrets-sync
  namespace: dev
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-storage
  target:
    name: web-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: web-frontend-auth-secret
    - secretKey: AUTH_KEYCLOAK_ID
      remoteRef:
        key: web-frontend-keycloak-id
    - secretKey: AUTH_KEYCLOAK_SECRET
      remoteRef:
        key: web-frontend-keycloak-secret
    - secretKey: AUTH_KEYCLOAK_ISSUER
      remoteRef:
        key: web-frontend-keycloak-issuer
    - secretKey: AUTH_URL
      remoteRef:
        key: web-frontend-url
    - secretKey: NEXT_PUBLIC_API_URL
      remoteRef:
        key: web-frontend-api-url
    - secretKey: NEXT_PUBLIC_WS_URL
      remoteRef:
        key: web-frontend-ws-url
