name: 2. Build services container, Test and Push to registry

on:
  push:
    branches:
     - dev

jobs:
  Build-Test-Push:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        id-token: write

    env:
        ARTIFACT_REGISTRY: ${{ secrets.REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPOSITORY }}
        TAG: staging
    
    steps:
      - name: clone_code
        uses: actions/checkout@v4
    
      - name: build_and_health_check
        run: | 
          docker compose -f docker_compose_for_testing/docker-compose.yml up -d
          
          echo "Waiting for services to be healthy..."
          # Đợi tối đa 60s cho các service ổn định
          timeout 60s bash -c 'until curl -s http://localhost:8000/health && \
                                     curl -s http://localhost:8001/health && \
                                     curl -s http://localhost:8002/health && \
                                     curl -s http://localhost:8003/health && \
                                     curl -s http://localhost:8004/health && \
                                     curl -s http://localhost:8005/health && \
                                     curl -s http://localhost:8006/health; do sleep 5; done'
          
          echo "Verifying health endpoints..."
          curl --fail http://localhost:8000/health || exit -1
          curl --fail http://localhost:8001/health || exit -1
          curl --fail http://localhost:8002/health || exit -1
          curl --fail http://localhost:8003/health || exit -1
          curl --fail http://localhost:8004/health || exit -1
          curl --fail http://localhost:8005/health || exit -1
          curl --fail http://localhost:8006/health || exit -1
          
          echo "All services are healthy!"

      - name: authentication with google
        uses: google-github-actions/auth@v2
        id: auth
        with:
          service_account: ${{ secrets.CICD_SA_EMAIL }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          token_format: 'access_token'

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Push images to Artifact Registry
        run: docker compose -f docker_compose_for_testing/docker-compose.yml push collectors forecast-service sentiment-service market-data-service
